### ISSUE TITLE
Add data/privacy consent 

### ISSUE THREAD

**Issue by joaopgrassi** [dotnet/nuget-trends#126]
I know it sucks, but I think we should add a "consent" message somewhere in the page since we collect analytics. Need to find a nice and unobtrusive way of doing it. Maybe even disabling everything by default?

This is to shield us so we don't run into GDPR and similar issues.

**Comment by bruno-garcia** [comment]
I rather we annonymise the data: `{ ‘anonymize_ip’: true } `
This seem useful: https://law.stackexchange.com/questions/35528/is-it-really-possible-to-use-google-analytics-without-consent-and-if-so-why-ex

IMHO it's better to rip off google analytics than have a banner. Super annoying, and we don't even use these stats

**Comment by joaopgrassi** [comment]
Yes I agree. I read so many things about it and was still not sure about it because there are so many nuances.. so I went with the nuke approach and removed it altogether from my blog.

**Comment by bruno-garcia** [comment]
Removed google analytics: https://github.com/dotnet/nuget-trends/commit/680640c7d1ffe05f0e55cc81188958037485d10b

Literally never looked at it in 4 years or more
