### ISSUE TITLE
Search results show old results

### ISSUE THREAD

**Issue by joaopgrassi** [dotnet/nuget-trends#143]
Follow the steps the reproduce:

1. search for a package and wait for the results
2. remove the text and leave the field (click somewhere)
3. come back to the input
4. old results are shown

I believe that old results should not be shown in this case. If you leave the text in there, it's ok to show the old results though.

**Comment by bruno-garcia** [comment]
I thought it was a cool feature. I'd search: `Sentry`, click. Then click again and see : `Sentry.AspNetCore` so I could just click on it.

But I get the motivation of it. Someone's bug is someone else's feature though :)

**Comment by joaopgrassi** [comment]
Hum I see your point. I got asked by 2 ppl about it, so I thought to just fix haha. We can discuss more if you believe it has value.
