### ISSUE TITLE
Discrepancy between NuGet numbers reported on Nuget.org and NugetTrends.com?

### ISSUE THREAD

**Issue by michael-hawker** [dotnet/nuget-trends#171]
The [ColorCode packages here](https://www.nuget.org/packages/ColorCode.Core/) on NuGet each show over 900k downloads:

![image](https://user-images.githubusercontent.com/24302614/131711190-4ae31ced-74e8-4c46-9ba0-0506337a92c2.png)

But show just under 600k on [NuGetTrends](https://www.nugettrends.com/packages?months=24&ids=ColorCode.Core&ids=ColorCode.UWP):

![image](https://user-images.githubusercontent.com/24302614/131711312-1700432f-ea2f-4028-98c9-bdc0c20dbe55.png)

Which is right?

**Comment by chr-ber** [comment]
This issue should be no longer valid, the linked bug issue has been closed.

The packages referred in the initial message have also matching download counts now.

![image](https://user-images.githubusercontent.com/31539452/209435137-09a56f0e-03f6-4082-afe5-421889130da0.png)
![image](https://user-images.githubusercontent.com/31539452/209435102-33f5f7e7-44e3-49bb-baba-20dd1b603532.png)

![image](https://user-images.githubusercontent.com/31539452/209435147-b640a439-0550-4689-8011-acba6f02ae03.png)

**Comment by bruno-garcia** [comment]
Thanks @chr-ber ! Closing
