### ISSUE TITLE
ng serve always stops running

### ISSUE THREAD

**Issue by tonyqus** [dotnet/nuget-trends#188]
I got the following error while running _npm run ng serve_

`An unhandled exception occurred: Script file tmp/release.js does not exist.`

I confirmed I've run _npm run build_ to generate the tmp/release.js. However, I got the following error:

`The system cannot find the path specified. `

Is there any windows environment variable I missed?

Environment Info
- Node version: v16.10.0
- npm version: 7.24.0

**Comment by joaopgrassi** [comment]
Yes, it's an issue that was introduced some time ago. There's a bug for it and some ideas on how to fix it: https://github.com/dotnet/nuget-trends/issues/177

**Comment by tonyqus** [comment]
duplicate issue.
