### ISSUE TITLE
New data is missing.

### ISSUE THREAD

**Issue by KristofferStrube** [dotnet/nuget-trends#214]
It seems like there isn't coming new data in the graph.

An example is this: https://nugettrends.com/packages?ids=KristofferStrube.Blazor.FileSystemAccess&months=10

There are no graph entries for 2023.

**Comment by bruno-garcia** [comment]
Thanks for pointing out @KristofferStrube , I'll take a look at this

**Comment by bruno-garcia** [comment]
Alright it's running again. There was an error in Sentry which I ignored during the holidays and forgot about, sorry about that.
