### ISSUE TITLE
Missing data.

### ISSUE THREAD

**Issue by KristofferStrube** [dotnet/nuget-trends#233]
Hey, it seems we are missing new data in the graph again.

This might be the same reason as a case earlier this year that I raised in this resolved issue: https://github.com/dotnet/nuget-trends/issues/214

**Comment by bruno-garcia** [comment]
Recently moved to Azure but had several errors raised due failure to connect to psotgres, etc.
Old box still running and collecting data but I need to look into this Azure resources. Got the lowest spec boxes/app services and doesn't seem to be enough

**Comment by KristofferStrube** [comment]
All good. Let me know if there is anything I can help with or test.

Did you get the Azure resource sponsored from the .NET Foundation or is it out of your own pocket?

**Comment by bruno-garcia** [comment]
Got some Azure credits from Microsoft (not from the foundation directly). 
I need to take a few hours to fix things up and check if the credits will be enough to keep this running. I'll need a few weeks unfortunately before I'll be able to sit and work on this, sorry.

**Comment by bruno-garcia** [comment]
I'll close this since we have enough data going to see the trends. Never got around pulling from the old server to fill that gap though
