### ISSUE TITLE
Truncate white-space on search

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet/nuget-trends#63]
I often copy a package name from somewhere which includes a whitespace.
That makes it so I get no results, and also no feedback:

~* Trim input to search~
* Give feedback if no result for search

**Comment by frosch95** [comment]
Hi,
I looked at the code and I am a little irritated by the label front-end. 
Isn't it "just" a trim in the PackageController?

And I would'nt give additional feedback when nothing is found.
It is normal REST behaviour that a search result is an empty list in that case

If I am correct with my assumptions, I would like to do a PR.

**Comment by bruno-garcia** [comment]
@frosch95 Trimming on the controller would already help a lot, we would appreciate a PR. Thanks.

**Comment by frosch95** [comment]
@bruno-garcia Oh, I have now seen which frontend was meant. I completely missed the SPA, as my editor just showed the controller with a full project search for the term "search". 

I can also help with the SPA client, if you like.

**Comment by joaopgrassi** [comment]
We should also apply this in the `search-input.component.ts` around line 40. As a bonus, we could also display a toaster notification if no results were found, like Bruno suggested.
